channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=24.2
- pip:
  - mlflow==2.15.1
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - psutil==5.9.8
  - scikit-learn==1.5.0
  - scipy==1.13.1
name: mlflow-env
